name: 'Lint checks'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - develop
      - 'releases/*'

jobs:
  lint-checks:
    name: Lint checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
